#!/bin/bash

ENVIRONMENT=$(echo "$CONTEXT" | jq -r .scope.dimensions.environment)
SERVICE=$(basename "$(echo "$CONTEXT" | jq -r '.application.repository_url')-kubernetes" | cut -c1-63)
VERSION=$(echo "$CONTEXT" | jq -r .release.semver)
TEAM=$(echo "$CONTEXT" | jq -r .application.metadata.scaffolding.project_details.tribe_name)

ARCHITECTURE=$(echo "$CONTEXT" | jq -r .application.metadata.scaffolding.architecture_type)

#admission.datadoghq.com/java-lib.version: "v1.50.0"
#admission.datadoghq.com/python-lib.version: "v3.9.3"
#admission.datadoghq.com/js-lib.version:  "v5.56.0"
#admission.datadoghq.com/ruby-lib.version: "v2.17.0"
#admission.datadoghq.com/dotnet-lib.version: "v3.19.0"

case "$ARCHITECTURE" in
  "react-"* | "js-"*)
    TECHNOLOGY=nodejs
    DATADOG_LIB_VERSION=v5.56.0
    ;;
  "spring-boot-"* | "java-"*)
      TECHNOLOGY=java
      DATADOG_LIB_VERSION=v1.5.0
      ;;
  "python-"*)
      TECHNOLOGY=python
      DATADOG_LIB_VERSION=v3.9.3
      ;;
  "ruby-"*)
      TECHNOLOGY=ruby
      DATADOG_LIB_VERSION=v2.17.0
      ;;
  "dotnet-"*)
      TECHNOLOGY=dotnet
      DATADOG_LIB_VERSION=v3.19.0
      ;;
  *)
    TECHNOLOGY=
    DATADOG_LIB_VERSION=
    echo "There is no known datadog lib for architecture: $ARCHITECTURE, the technology-specific annotation will be skipped."
    ;;
esac

DATADOG_LABELS=$(jq -n --arg env "$ENVIRONMENT" --arg service "$SERVICE" --arg version "$VERSION" '{
  "tags.datadoghq.com/env": $env,
  "tags.datadoghq.com/service": $service,
  "tags.datadoghq.com/version": $version,
  "admission.datadoghq.com/enabled": "true"
}')

DATADOG_ANNOTATIONS=$(jq -n --arg team "$TEAM" --arg java_lib_version "$JAVA_LIB_VERSION" '{
  "admission.datadoghq.com/config.mode": "socket",
  "ad.datadoghq.com/tags": ("{\"team\": \"" + $team + "\"}")
}')

if [[ -n "$TECHNOLOGY" ]]; then
  DATADOG_ANNOTATIONS=$(echo "$DATADOG_ANNOTATIONS" | jq --arg technology "$TECHNOLOGY" --arg lib_version "$DATADOG_LIB_VERSION" '
    . + { ("admission.datadoghq.com/" + $technology + "-lib.version"): $lib_version }
  ')
fi

MODIFIERS=$(echo "$CONTEXT" | jq .k8s_modifiers)

MODIFIERS=$(echo "$MODIFIERS" | jq --argjson datadog_annotations "$DATADOG_ANNOTATIONS" --argjson datadog_labels "$DATADOG_LABELS" '
  .deployment.annotations = ((.deployment.annotations // {}) + $datadog_annotations) |
  .deployment.labels = ((.deployment.labels // {}) + $datadog_labels)
')

CONTEXT=$(echo "$CONTEXT" | jq  --argjson modifiers "$MODIFIERS"  '.k8s_modifiers = $modifiers')

echo "Adding datadog annotations:"
echo "$DATADOG_ANNOTATIONS" | jq .

echo "Adding datadog labels:"
echo "$DATADOG_LABELS" | jq .