#!/bin/bash

ASSET_PLATFORM=$(echo "$CONTEXT" | jq -r .asset.platform)

MODIFIERS=$(echo "$CONTEXT" | jq .k8s_modifiers)


if [[ "$ASSET_PLATFORM" == "arm_64" ]]; then
  TOLERATIONS='[{"key": "architecture", "operator": "Equal", "value": "arm64", "effect": "NoSchedule"}]'
  NODESELECTOR='{"kubernetes.io/arch": "arm64"}'
  echo "The asset is built for arm, adding tolerations and nodeSelector to the deployment"
  echo "$TOLERATIONS" | jq .
  echo "$NODESELECTOR" | jq .

  MODIFIERS=$(echo "$MODIFIERS" | jq --argjson tolerations "$TOLERATIONS" --argjson nodeselector "$NODESELECTOR" '
    if .deployment then
      .deployment.tolerations = (.deployment.tolerations // []) + $tolerations |
      .deployment.nodeselector = $nodeselector
    else
      .deployment = {"tolerations": $tolerations, "nodeselector": $nodeselector}
    end
  ')

  CONTEXT=$(echo "$CONTEXT" | jq  --argjson modifiers "$MODIFIERS"  '.k8s_modifiers = $modifiers')
fi
