#!/bin/bash

echo "Creating ingress for service $SERVICE_NAME with domain $SERVICE_DOMAIN"

echo "Creating public ingress..."

INGRESS_FILE="$OUTPUT_DIR/ingress-$SERVICE_ID-public.yaml"
CONTEXT_PATH="$OUTPUT_DIR/context-$SERVICE_ID.json"

echo "$CONTEXT" > "$CONTEXT_PATH"

echo "Building Template: $TEMPLATE to $INGRESS_FILE"

gomplate -c .="$CONTEXT_PATH" \
  --file "$TEMPLATE" \
  --out "$INGRESS_FILE"

rm "$CONTEXT_PATH"